import { useState } from "react";
import { useNavigate } from "react-router-dom";

const meals = [
  {
    day: "Monday", date: "25 May", emoji: "🇻🇳",
    title: "Pho Gà",
    subtitle: "Vietnamese chicken noodle soup · DIY toppings at the table",
    kids: "~70g noodles + ~80g chicken each, mild broth. Spring onions on side.",
    adult: "Full bowl + coriander, chilli, lime, hoisin 🌶️",
    adultRef: "Adapted from Vicky Pham",
    adultRefUrl: "https://www.vickypham.com/blog/vietnamese-chicken-noodle-soup-pho-ga",
    dessert: null,
    ingredients: [
      "800g chicken legs or bone-in thighs",
      "1.5L good quality chicken stock",
      "180g flat rice noodles (bánh phở)",
      "3cm fresh ginger, halved",
      "1 onion, halved",
      "2 star anise",
      "1 cinnamon stick",
      "3 cloves",
      "2 tbsp fish sauce",
      "— Toppings (on the table) —",
      "Bean sprouts, handful",
      "Fresh coriander",
      "2 spring onions, sliced",
      "1 lime, cut in wedges",
      "1 red chilli, sliced (adult)",
      "Hoisin sauce (adult)",
    ],
    steps: [
      "Char ginger & onion: place cut side down on gas flame or under grill until lightly blackened, 2–3 min. Key for a deep fragrant broth.",
      "Bring stock + 500ml water to boil. Add charred ginger, onion, star anise, cinnamon, cloves.",
      "Add chicken. Simmer 25–30 min on medium-low until cooked through.",
      "Remove chicken. Shred meat finely, discard skin & bones.",
      "Strain broth through fine sieve. Return to pot. Season with fish sauce — taste as you go.",
      "Soak rice noodles in warm water 20 min, then cook in boiling water 1–2 min. Drain.",
      "Assemble bowls: noodles, shredded chicken, hot broth poured over.",
      "Bring all toppings to table — everyone adds their own! Kids: spring onions only. Adult: coriander, chilli, lime, hoisin.",
    ],
  },
  {
    day: "Tuesday", date: "26 May", emoji: "🇻🇳",
    title: "Cá Kho Tộ",
    subtitle: "Vietnamese caramelised fish · steamed rice · greens · make double for Wednesday!",
    kids: "~80g fish each, ~160g cooked rice each. Glaze on the side.",
    adult: "Full portion + sliced chilli & fresh coriander 🌶️",
    adultRef: "Adapted from The Ravenous Couple",
    adultRefUrl: "https://theravenouscouple.com/ca-kho-to-vietnamese-braised-fish-in-clay-pot/",
    dessert: null,
    ingredients: [
      "900g salmon fillets or catfish, thick pieces (double batch)",
      "480g jasmine rice — cook half tonight, half Wed",
      "5 tbsp fish sauce",
      "4 tbsp sugar (for caram
